# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfcheck < Formula
  desc "Template for go project and tap."
  homepage "https://github.com/itsdalmo/tfcheck"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/itsdalmo/tfcheck/releases/download/v0.1.0/tfcheck-0.1.0-darwin-amd64.tar.gz"
      sha256 "333c5e4133c2cf9e62d885e79990b42bdfc12067fa14ef9844a7926a50417a91"

      def install
        bin.install "tfcheck"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/itsdalmo/tfcheck/releases/download/v0.1.0/tfcheck-0.1.0-darwin-arm64.tar.gz"
      sha256 "732a4e5fb58b45b3861b8da44c256a931783b389a9910c35a7750e16ec2d09d5"

      def install
        bin.install "tfcheck"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/itsdalmo/tfcheck/releases/download/v0.1.0/tfcheck-0.1.0-linux-arm64.tar.gz"
      sha256 "0c1491da21e3060893d64b204d62741e5b855be8294a0735e2212b34de3e19c8"

      def install
        bin.install "tfcheck"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/itsdalmo/tfcheck/releases/download/v0.1.0/tfcheck-0.1.0-linux-amd64.tar.gz"
      sha256 "4ad97deaa5eba8c22414ac95377da96edcaa73197f4e91e7288ad43b3c6e94bb"

      def install
        bin.install "tfcheck"
      end
    end
  end

  test do
    system "#{bin}/tfcheck --version"
  end
end
